### ISSUE TITLE
metadata.json permissions

### ISSUE THREAD

**Issue by rjhornsby** [example42/puppet-resolver#10]
In the Puppet Forge module (the one that you get with `puppet module install`), the metadata.json file has permissions 640.  It should be 644.  This creates a slightly confusing error from Puppet when it tries to compile the catalog.

Alternatively, if your modules directory is owned by the user running the puppet master process, you won't see this issue.  It's only when the module files are owned by another user (i.e. root).

For completeness, the error looks something like this

```
Error 400 on SERVER: Evaluation Error: Error while evaluating a
Function Call, Permission denied - 
/etc/puppetlabs/code/modules/resolver/metadata.json 
at /etc/puppetlabs/code/environments/production/manifests/site.pp:1.1
on node yournode.yourorg.com
```

The code checked into Github is fine - the repo contains the correct permissions.

**Comment by alvagante** [comment]
Just uplodaed to the forge a version with the correct permissions. Please let me know if it works also for you.

**Comment by rjhornsby** [comment]
yep, works great. thanks!

Closing as fixed.
