### ISSUE TITLE
Cannot use empty string as a class name

### ISSUE THREAD

**Issue by iyappan-dcis** [example42/puppet-resolver#11]
## Expected Behavior 
Module to update the resolv.conf file of my server

## Actual Behavior
Getting the below error
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Cannot use empty string as a class name (file: /etc/puppetlabs/code/environments/development/modules/resolver/manifests/init.pp, line: 229, column: 5) on node web

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
os => {
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.4.1708",
    major => "7",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}

  1. Version of Puppet and of the module
puppetserver-5.0.0-1.el7.noarch
puppet-agent-5.5.0-1.el7.x86_64
mod 'example42-resolver', '2.0.15'

  1. The relevant Puppet code and eventually Hiera data
resolver::dns_domain: 'xxx.com'
resolver::dns_servers:
  - xx.xx.xx.xx
  - yy.yy.yy.yy
resolver::search:
  - xxx.com
resolver::options:
  rotate: ''
  timeout: 5

**Comment by alvagante** [comment]
This https://github.com/example42/puppet-resolver/commit/69b11592fd1d29299bf63775096b6180727d2e6b solves the issue.
Note anyway that the module is very old and not actively maintained. You can achieve the same (and much more) with this profile from psick module: https://github.com/example42/puppet-psick/blob/master/manifests/dns/resolver.pp

**Comment by iyappan-dcis** [comment]
@alvagante Thank you very much for your help. But I have one question here, I have been using this module since a year on few puppet servers, They are still running good without any errors. But why am I getting such errors on this server alone?

Note: I am using the same version of this module on all the puppet servers.

Thanks in Advance.

**Comment by alvagante** [comment]
@iyappan-dcis Is this server using a different puppet version? This fix address a problem which arises with Puppet 4 future parser (empty strings are not false anymore) and, maybe, a check on the impossibility to include empty string classes with Puppet 5.
